### PR TITLE
Fixes 18919 - Java-driven builds fail with new closure compiler

### PR DESCRIPTION
**Pull request by vansimke**
* updated closure.js to implement the same fix as was added to optimizeRunner.js to fix Java-driven builds

* moved setting of deadAssignmentElimination to be above application of  settings from build profile to allow user to override, if they desire

### CODE REVIEW

**Comment by sindilevich** [comment]
@vansimke, thank you! Before I go forward checking the fix, I see _closure.js_ lacks much of the build features that _optimizeRunner,js_ has. See https://github.com/vansimke/util/blob/15372bb4f524cc3f6066f106bd3967c40ce8eb7f/build/optimizeRunner.js#L105-L243.

**Comment by vansimke** [comment]
Closed via https://github.com/dojo/util/commit/2005694744068814338d3a583071cbb2264a2d09

**Comment by vansimke** [comment]
Sorry, you have a good point. I'm trying to change as few things as possible to prevent the chance of introducing new regressions, but this should have been included. It is in master now.

**Comment by sindilevich** [comment]
@vansimke, you think you'd add the missing build features too, before dojo 1.12 goes release?

**Comment by vansimke** [comment]
Yes, we'd include those changes (currently at the tip of the master branch) into 1.12.

**Comment by sindilevich** [comment]
@vansimke, see my comment here, please: https://github.com/dojo/util/commit/bd14cf587be958c3d38aad91bdde9a4f43f900f4#commitcomment-20156095.

**Comment by vansimke** [comment]
@sindilevich I've added that here: https://github.com/dojo/util/pull/55. Let's use that PR to continue this discussion since I've already closed and merged this one.

**Pull request closed without merging**
