### PR TITLE
add support for compilation levels with Java-driven builds

### PR DESCRIPTION
**Pull request by vansimke**

### CODE REVIEW

**Comment by vansimke** [comment]
This PR was created to add features that were missed in [PR 54](https://github.com/dojo/util/pull/54)

**Comment by sindilevich** [comment]
@vansimke, thanks!

**Comment by vansimke** [comment]
Closed via https://github.com/dojo/util/commit/21e99ff9ce6b815647f2638274aeb9a350ceff9c

**Comment by sindilevich** [comment]
@vansimke, when a Java-driven build gets to apply the Google Closure Compiler it throws errors on every file it processes, like the one below:

> starting executing global optimizations...
> starting writing resources...
> error(356) The optimizer threw an exception; the module probably contains syntax errors. module identifier: put-selector/put; exception: TypeError: Cannot read property "compilationLevel" from undefined

**Comment by sindilevich** [comment]
I think `bc.optimizeOptions` in https://github.com/vansimke/util/blob/69d1bf30b81482e1fe7ffbe24ac278a2d07bd404/build/transforms/optimizer/closure.js#L55 is `undefined`.

**Pull request closed without merging**
